[general]
title = "Pt training"
mode = "training"

[training]
feffpath = "./feff/Pt_feff0001.dat"
training_set_dir = "./training_set"
num_examples = 10000
spectrum_noise = true
noise_range = [ 0.0, 0.01,]
k_range = [ 2.5, 12.5,]
k_weight = 2
train_size_ratio = 0.8
val_size_ratio = 0.1
test_size_ratio = 0.1

[neural_network]
model_name = "Pt"
model_dir = "./model"
checkpoint_dir = "./checkpoint"
checkpoint_name = "Pt"

[training.param_ranges]
s02 = [ 0.75, 1.2,]
degen = [ 4.0, 13.0,]
deltar = [ -0.2, 0.2,]
sigma2 = [ 0.001, 0.02,]
e0 = [ -10, 10,]

[neural_network.hyperparameters]
epochs = 100
batch_size = 32
learning_rate = 0.001

[neural_network.architecture]
type = "MLP"
activation = "relu"
output_activation = "linear"
output_dim = 4
hidden_dims = [ 516, 516, 516, 516,]
