[general]
title = "Example training config"
mode = "training"
output_dir = "output"
input_type = "q"

[training]
feffpath = "Pt_feff0001.dat"
training_set_dir = "training_set"
training_data_prefix = "Example training_data"
num_examples = 10000
spectrum_noise = false
noise_range = [ 0.0, 0.0,]
k_range = [ 2, 14,]
k_weight = 2
r_range = [ 1.7, 3.0,]
train_size_ratio = 0.8
val_size_ratio = 0.2
test_size_ratio = 0
training_noise = true
training_noise_range = [ 0.0, 0.01,]

[neural_network]
model_name = "Example"
model_dir = "model"
checkpoint_dir = "checkpoint"
checkpoint_name = "Example"

[experiment]
dataset_names = [ "foil",]
dataset_dir = [ "path/to/your/foil.chik",]
k_range = [ 2, 14,]
r_range = [ 1.7, 3.0,]
k_weight = 2

[training.param_ranges]
s02 = [ 0.75, 1.2,]
degen = [ 4.0, 13.0,]
deltar = [ -0.2, 0.2,]
sigma2 = [ 0.001, 0.02,]
e0 = [ -10, 10,]

[neural_network.hyperparameters]
epochs = 1000
batch_size = 1000
learning_rate = 0.001

[neural_network.architecture]
type = "MLP"
activation = "leakyrelu"
output_activation = "linear"
output_dim = 4
hidden_dims = [ 516, 516,]
dropout_rates = [ 0, 0,]
weight_decay = 0.0
filter_sizes = [ 0,]
kernel_sizes = [ 0,]