[general]
title = "Example inference config"
mode = "inference"
output_dir = "output"
input_type = "q"

[neural_network]
model_name = "Example"
model_dir = "model"
checkpoint_dir = "checkpoint"
checkpoint_name = "Example"

[experiment]
dataset_names = [ "foil", "sample1", "sample2",]
dataset_dir = [ "path/to/your/foil.chik", "path/to/your/sample1.chik", "path/to/your/sample2.chik",]
k_range = [ 2, 14,]
r_range = [ 1.7, 3.0,]
k_weight = 2

[artemis]
result = [ [ 10.3, -0.0099, 0.0057, -0.5,], [ 7.6, -0.008, 0.0073, -1.5,], [ 7.8, 0.063, 0.0078, -1.3,],]
unc = [ [ 0.2, 0.0009, 0.0001, 0.2,], [ 0.4, 0.002, 0.0003, 0.3,], [ 0.3, 0.002, 0.0002, 0.3,],]

[neural_network.architecture]
type = "MLP"
activation = "leakyrelu"
output_activation = "linear"
output_dim = 4
hidden_dims = [ 516, 516,]
dropout_rates = [ 0, 0,]
weight_decay = 0.0
filter_sizes = [ 0,]
kernel_sizes = [ 0,]